In [208]:
import pandas as pd
df = pd.read_csv("book_dataset.csv")
df.head()

,title,titleComplete,description,genres,isbn,publisher,author,characters,places,ratingHistogram,ratingsCount,reviewsCount,numPages,language
0,Project Hail Mary,Project Hail Mary,Ryland Grace is the sole survivor on a despera...,"['Science Fiction Fantasy', 'Audiobook', 'Fant...",0593135202,Ballantine Books,['Andy Weir'],"['Ryland Grace', 'Rocky']","['Tau Ceti System', 'Outer Space']","[1917, 5775, 29742, 116572, 266669]",420675.0,53538.0,476.0,English
1,The Talented Mr. Ripley,"The Talented Mr. Ripley (Ripley, #1)","Since his debut in 1955, Tom Ripley has evolve...","['Novels', 'Noir', 'Classics', 'Italy', 'Suspe...",0393332144,W. W. Norton Company,['Patricia Highsmith'],"['Freddie Miles', 'Tom Ripley', 'Dickie Greenl...","['Italy', 'New York City, New York', 'Italian ...","[1483, 3902, 17161, 34467, 24270]",81283.0,5146.0,288.0,English
2,More Than This,More Than This,"A boy drowns, desperate and alone in his final...","['Queer', 'Fantasy', 'Contemporary', 'LGBT', '...",1406350486,Walker Books Ltd,['Patrick Ness'],['Seth Wearing'],NaN,"[1441, 3672, 12295, 23873, 21208]",62489.0,8194.0,480.0,English
3,After Forever Ends,After Forever Ends,Orphaned by her mother and brushed off by her ...,"['Chick Lit', 'Fantasy', 'Coming Of Age', 'Con...",NaN,Gingersnap Press,['Melodie Ramone'],NaN,NaN,"[81, 119, 205, 365, 750]",1520.0,241.0,564.0,English
4,A Bird Without Wings,A Bird Without Wings,"After an impoverished and indigent childhood, ...","['Contemporary', 'Contemporary Romance', 'Roma...",NaN,Smashwords,['Roberta Pearce'],NaN,NaN,"[7, 6, 26, 49, 91]",179.0,31.0,NaN,English

In [209]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14712 entries, 0 to 14711
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            14712 non-null  str
 1   titleComplete    14712 non-null  str
 2   description      14712 non-null  str
 3   genres           14712 non-null  str
 4   isbn             11738 non-null  str
 5   publisher        14042 non-null  str
 6   author           14710 non-null  str
 7   characters       7177 non-null   str
 8   places           5971 non-null   str
 9   ratingHistogram  14709 non-null  str
 10  ratingsCount     14709 non-null  float64
 11  reviewsCount     14692 non-null  float64
 12  numPages         14467 non-null  float64
 13  language         14358 non-null  str
dtypes: float64(3), str(11)
memory usage: 1.6 MB

In [210]:
df["ratingsCount"].describe()

count    1.470900e+04
mean     6.837311e+04
std      2.626154e+05
min      3.000000e+00
25%      3.809000e+03
50%      1.698700e+04
75%      5.024600e+04
max      9.276475e+06
Name: ratingsCount, dtype: float64

In [211]:
def get_similar_books(title, n=10):
    idx = df[df["title"] == title].index
    if len(idx) == 0:
        return "Book not found"
    idx = idx[0]
    scores = list(enumerate(similarity[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)[1:n+1]
    book_indices = [i[0] for i in scores]
    return df.iloc[book_indices][["title", "author", "genres"]]

In [212]:
get_similar_books("Harry Potter and the Sorcerer's Stone")

,title,author,genres
1609,Harry Potter and the Sorcerer's Stone,['J.K. Rowling'],"['Audiobook', 'Childrens', 'Adventure', 'Magic..."
1900,A Wind in the Door,"[""Madeleine L'Engle"", 'Jody A. Lee']","['Audiobook', 'Childrens', 'Adventure', 'Middl..."
29,The Sword of Summer,['Rick Riordan'],"['Audiobook', 'Fantasy', 'Childrens', 'Adventu..."
1480,A Swiftly Tilting Planet,"[""Madeleine L'Engle"", 'Jody A. Lee']","['Time Travel', 'Childrens', 'Adventure', 'Mid..."
1545,Matilda,"['Quentin Blake', 'Roald Dahl']","['Audiobook', 'Childrens', 'Magic', 'Middle Gr..."
1567,The BFG,"['Quentin Blake', 'Roald Dahl']","['Audiobook', 'Juvenile', 'Childrens', 'Advent..."
1917,Ozma of Oz,['L. Frank Baum'],"['Juvenile', 'Audiobook', 'Childrens', 'Advent..."
2396,The Worst Witch At Sea,['Jill Murphy'],"['Audiobook', 'Boarding School', 'Childrens', ..."
2610,The Road to Oz,['L. Frank Baum'],"['Audiobook', 'Juvenile', 'Childrens', 'Advent..."
13234,Harry Potter and the Philosopher’s Stone,['J.K. Rowling'],"['Middle Grade', 'Adventure', 'Classics', 'Mag..."

In [213]:
get_similar_books("some other title you're familiar with")

'Book not found'

In [214]:
df[df["title"].str.contains("Potter", case=False, na=False)]["title"]

86       Harry Potter and the Cursed Child: Parts One a...
362                            Harry Potter Series Box Set
462                Harry Potter and the Chamber of Secrets
496               Harry Potter and the Prisoner of Azkaban
499                   Harry Potter and the Deathly Hallows
654            Harry Potter and the Methods of Rationality
1601               Harry Potter and the Chamber of Secrets
1609                 Harry Potter and the Sorcerer's Stone
3326             Harry Potter and the Order of the Phoenix
4315               James Potter and the Vault of Destinies
6775                     Harry Potter Boxed Set, Books 1-5
8194                              The Harry Potter Trilogy
10507    Harry Potter and the Cursed Child: Parts One a...
12489                                  From Potter's Field
13234             Harry Potter and the Philosopher’s Stone
Name: title, dtype: str

In [215]:
get_similar_books("Harry Potter and the Sorcerer's Stone")

,title,author,genres
1609,Harry Potter and the Sorcerer's Stone,['J.K. Rowling'],"['Audiobook', 'Childrens', 'Adventure', 'Magic..."
1900,A Wind in the Door,"[""Madeleine L'Engle"", 'Jody A. Lee']","['Audiobook', 'Childrens', 'Adventure', 'Middl..."
29,The Sword of Summer,['Rick Riordan'],"['Audiobook', 'Fantasy', 'Childrens', 'Adventu..."
1480,A Swiftly Tilting Planet,"[""Madeleine L'Engle"", 'Jody A. Lee']","['Time Travel', 'Childrens', 'Adventure', 'Mid..."
1545,Matilda,"['Quentin Blake', 'Roald Dahl']","['Audiobook', 'Childrens', 'Magic', 'Middle Gr..."
1567,The BFG,"['Quentin Blake', 'Roald Dahl']","['Audiobook', 'Juvenile', 'Childrens', 'Advent..."
1917,Ozma of Oz,['L. Frank Baum'],"['Juvenile', 'Audiobook', 'Childrens', 'Advent..."
2396,The Worst Witch At Sea,['Jill Murphy'],"['Audiobook', 'Boarding School', 'Childrens', ..."
2610,The Road to Oz,['L. Frank Baum'],"['Audiobook', 'Juvenile', 'Childrens', 'Advent..."
13234,Harry Potter and the Philosopher’s Stone,['J.K. Rowling'],"['Middle Grade', 'Adventure', 'Classics', 'Mag..."

In [216]:
get_similar_books("The Worst Witch At Sea")

,title,author,genres
1601,Harry Potter and the Chamber of Secrets,"['J.K. Rowling', 'Mary GrandPré']","['Audiobook', 'Childrens', 'Adventure', 'Magic..."
1609,Harry Potter and the Sorcerer's Stone,['J.K. Rowling'],"['Audiobook', 'Childrens', 'Adventure', 'Magic..."
29,The Sword of Summer,['Rick Riordan'],"['Audiobook', 'Fantasy', 'Childrens', 'Adventu..."
1545,Matilda,"['Quentin Blake', 'Roald Dahl']","['Audiobook', 'Childrens', 'Magic', 'Middle Gr..."
1567,The BFG,"['Quentin Blake', 'Roald Dahl']","['Audiobook', 'Juvenile', 'Childrens', 'Advent..."
1900,A Wind in the Door,"[""Madeleine L'Engle"", 'Jody A. Lee']","['Audiobook', 'Childrens', 'Adventure', 'Middl..."
1917,Ozma of Oz,['L. Frank Baum'],"['Juvenile', 'Audiobook', 'Childrens', 'Advent..."
2610,The Road to Oz,['L. Frank Baum'],"['Audiobook', 'Juvenile', 'Childrens', 'Advent..."
84,The Serpent's Shadow,['Rick Riordan'],"['Young Adult Fantasy', 'Fantasy', 'Childrens'..."
107,The Throne of Fire,['Rick Riordan'],"['Young Adult Fantasy', 'Fantasy', 'Childrens'..."

In [217]:
get_similar_books("The BFG")

,title,author,genres
2610,The Road to Oz,['L. Frank Baum'],"['Audiobook', 'Juvenile', 'Childrens', 'Advent..."
1412,The Bad Beginning,"['Brett Helquist', 'Lemony Snicket']","['Audiobook', 'Juvenile', 'Childrens', 'Advent..."
1545,Matilda,"['Quentin Blake', 'Roald Dahl']","['Audiobook', 'Childrens', 'Magic', 'Middle Gr..."
1585,Charlie and the Chocolate Factory,"['Quentin Blake', 'Roald Dahl']","['Juvenile', 'Childrens', 'Adventure', 'Middle..."
1601,Harry Potter and the Chamber of Secrets,"['J.K. Rowling', 'Mary GrandPré']","['Audiobook', 'Childrens', 'Adventure', 'Magic..."
1609,Harry Potter and the Sorcerer's Stone,['J.K. Rowling'],"['Audiobook', 'Childrens', 'Adventure', 'Magic..."
1900,A Wind in the Door,"[""Madeleine L'Engle"", 'Jody A. Lee']","['Audiobook', 'Childrens', 'Adventure', 'Middl..."
2423,The Austere Academy,"['Brett Helquist', 'Michael Kupperman', 'Lemon...","['Audiobook', 'Juvenile', 'Childrens', 'Advent..."
9027,Half Magic,"['Edward Eager', 'N.M. Bodecker']","['Middle Grade', 'Adventure', 'Classics', 'Mag..."
29,The Sword of Summer,['Rick Riordan'],"['Audiobook', 'Fantasy', 'Childrens', 'Adventu..."

In [218]:
get_similar_books("The Cruel Prince")

,title,author,genres
247,A Court of Mist and Fury,['Sarah J. Maas'],"['Young Adult', 'Romance', 'Fantasy', 'Fantasy..."
299,A ​Court of Silver Flames,['Sarah J. Maas'],"['Young Adult', 'Romance', 'Fantasy', 'Fantasy..."
695,The Shadows Between Us,['Tricia Levenseller'],"['Young Adult', 'Romance', 'Fantasy', 'Fantasy..."
1174,Vow of Thieves,['Mary E. Pearson'],"['Young Adult', 'Romance', 'Fantasy', 'Fantasy..."
3259,Ruin and Rising,['Leigh Bardugo'],"['Adventure', 'Paranormal', 'Young Adult Fanta..."
3272,Glass Sword,['Victoria Aveyard'],"['Dystopia', 'Romance', 'Young Adult Fantasy',..."
4161,Siege and Storm,['Leigh Bardugo'],"['Adventure', 'Paranormal', 'Young Adult Fanta..."
4885,Once Upon a Broken Heart,['Stephanie Garber'],"['High Fantasy', 'Romance', 'Magic', 'Fiction'..."
5070,The Ballad of Never After,['Stephanie Garber'],"['High Fantasy', 'Romance', 'Magic', 'Fiction'..."
5344,The Ballad of Never After,['Stephanie Garber'],"['High Fantasy', 'Romance', 'Magic', 'Fiction'..."

In [219]:
df["description"].isnull().sum()

np.int64(0)

In [220]:
df = df.drop_duplicates(subset=["title", "author"])

In [221]:
print(df.shape)
df = df.drop_duplicates(subset=["title", "author"])
print(df.shape)

(12555, 14)
(12555, 14)

In [222]:
df["title"].apply(lambda x: repr(x)).value_counts().head(20)

title
'Torn'                6
'Twisted'             6
'Broken'              6
'The Awakening'       5
'Revelations'         5
'Awakening'           5
'Shadowland'          4
'Hidden'              4
'Shadows'             4
'Silence'             4
'Haunted'             4
'Collected Poems'     4
'Chosen'              4
'Gone'                4
'Retribution'         4
'The Gift'            4
'Legacy'              4
'Burned'              3
'Forever'             3
'Of Human Bondage'    3
Name: count, dtype: int64

In [223]:
uvicorn main:app --reload

SyntaxError: invalid syntax (3807844594.py, line 1)